version: '3.9'

services:
  nginx_service:
    image: cr.yandex/crp47mcttv0eg7au1nmh/nginx_balancer
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      update_config:
        order: start-first
    ports:
      - "62205:62225"
  backend_service:
    image: cr.yandex/crp47mcttv0eg7au1nmh/backend_service
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
    ports:
      - "62215:62225"
  yolo_service:
    image: cr.yandex/crp47mcttv0eg7au1nmh/yolo_service
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
      update_config:
        order: start-first
    ports:
      - "62225:62225"
  audio_service:
    image: cr.yandex/crp47mcttv0eg7au1nmh/audio_service
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
      update_config:
        order: start-first
    ports:
      - "62235:62225"