version: '3.9'

services:
  nginx_service:
    image: nginx_balancer
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      update_config:
        order: start-first
    ports:
      - "62205:62225"
  backend_service:
    image: backend_service
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
    ports:
      - "62215:62225"
  yolo_service:
    image: yolo_service
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
      update_config:
        order: start-first
    ports:
      - "62225:62225"
  audio_service:
    image: audio_service
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
      update_config:
        order: start-first
    ports:
      - "62235:62225"